# Generated by Django 3.1.2 on 2020-11-22 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('follower', 'follower'), ('like', 'like'), ('mention', 'mention')], max_length=20),
        ),
    ]
